"""empty message

Revision ID: 0e28b7d15c54
Revises: cdb24a4541fb
Create Date: 2022-06-15 03:20:53.365092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e28b7d15c54'
down_revision = 'cdb24a4541fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.create_foreign_key('fk_question_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False))
        batch_op.create_foreign_key('fk_answer_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
